#!/bin/bash

# this script uses lofreq to call variants
# using bam file from alignment of paired reads to a reference sequence
#
# Mark Stenglein 3/27/2017

id=$1

# 1330_28wpi_R1_fu.fastq.siv.paired_sorted.bam

bt_index=siv

fasta_file=${bt_index}.fa
bam_file=${id}_R1_fu.fastq.${bt_index}.paired_sorted.bam
bcf_file=${bam_file/bam/bcf}
vcf_file=${bcf_file/bcf/vcf}

## samtools faidx $fasta_file

# use lofreq to call variants
lofreq_vcf_file=${vcf_file/.vcf/.lofreq.vcf}
lofreq call-parallel --pp-threads 8 -f siv.fa -o $lofreq_vcf_file $bam_file


