#!/bin/bash

# This script is the main entry point for variant
# identification and tabulation
# it does the following steps:
#
# (1) run a pre-filtering script to remove low quality reads, basecalls, and to collapse
#     non-unique sequences
#
# (2) run bowtie to align (pre-filtered) reads to the SIV reference genome sequence
#
# (3) uses lofreq to call variants relative to the SIV reference sequence
#
# (4) analyzes variants to determine their genomic position, whether they are synonymous or not, etc.
#
#
# Mark Stenglein 3/27/2017
#
id=$1
bt_index=siv
gff=Stock_virus_consensus_v1.gff

# run pre-filtering script
./run_prefiltering $id

# use bowtie to align to SIV ref seq
./run_bt $id $bt_index

# use lofreq to call variants
./call_variants ${id}

vcf=${id}_R1_fu.fastq.${bt_index}.paired_sorted.lofreq.vcf

./analyze_variants $gff $vcf > ${id}_variant_alleles.lofreq.txt

